
    const stylesheet = document.styleSheets[0];
    stylesheet.insertRule(".child { height: 50px; width: 50px; }", 0);

    const center = document.querySelector(".center");

    //creates and defines the parentGrid element for FlexBox
    const parentGrid = document.createElement("div");
    parentGrid.setAttribute("id", "parent");
    parentGrid.style.height = "800px";
    parentGrid.style.width = "800px";
    parentGrid.style.border = "3px solid black";
    parentGrid.style.display = 'flex';
    parentGrid.style.justifyContent = 'center';
    parentGrid.style.alignItems = 'center';
    parentGrid.style.flexWrap = "wrap";

    //building out 256 div squares for the grid using DOM manipulations
    const square1 = document.createElement("div");
    square1.classList.toggle("child", true);
    const square2 = document.createElement("div");
    square2.classList.toggle("child", true);
    const square3 = document.createElement("div");
    square3.classList.toggle("child", true);
    const square4 = document.createElement("div");
    square4.classList.toggle("child", true);
    const square5 = document.createElement("div");
    square5.classList.toggle("child", true);
    const square6 = document.createElement("div");
    square6.classList.toggle("child", true);
    const square7 = document.createElement("div");
    square7.classList.toggle("child", true);
    const square8 = document.createElement("div");
    square8.classList.toggle("child", true);
    const square9 = document.createElement("div");
    square9.classList.toggle("child", true);
    const square10 = document.createElement("div");
    square10.classList.toggle("child", true);
    const square11 = document.createElement("div");
    square11.classList.toggle("child", true);
    const square12 = document.createElement("div");
    square12.classList.toggle("child", true);
    const square13 = document.createElement("div");
    square13.classList.toggle("child", true);
    const square14 = document.createElement("div");
    square14.classList.toggle("child", true);
    const square15 = document.createElement("div");
    square15.classList.toggle("child", true);
    const square16 = document.createElement("div");
    square16.classList.toggle("child", true);
    const square17 = document.createElement("div");
    square17.classList.toggle("child", true);
    const square18 = document.createElement("div");
    square18.classList.toggle("child", true);
    const square19 = document.createElement("div");
    square19.classList.toggle("child", true);
    const square20 = document.createElement("div");
    square20.classList.toggle("child", true);
    const square21 = document.createElement("div");
    square21.classList.toggle("child", true);
    const square22 = document.createElement("div");
    square22.classList.toggle("child", true);
    const square23 = document.createElement("div");
    square23.classList.toggle("child", true);
    const square24 = document.createElement("div");
    square24.classList.toggle("child", true);
    const square25 = document.createElement("div");
    square25.classList.toggle("child", true);
    const square26 = document.createElement("div");
    square26.classList.toggle("child", true);
    const square27 = document.createElement("div");
    square27.classList.toggle("child", true);
    const square28 = document.createElement("div");
    square28.classList.toggle("child", true);
    const square29 = document.createElement("div");
    square29.classList.toggle("child", true);
    const square30 = document.createElement("div");
    square30.classList.toggle("child", true);
    const square31 = document.createElement("div");
    square31.classList.toggle("child", true);
    const square32 = document.createElement("div");
    square32.classList.toggle("child", true);
    const square33 = document.createElement("div");
    square33.classList.toggle("child", true);
    const square34 = document.createElement("div");
    square34.classList.toggle("child", true);
    const square35 = document.createElement("div");
    square35.classList.toggle("child", true);
    const square36 = document.createElement("div");
    square36.classList.toggle("child", true);
    const square37 = document.createElement("div");
    square37.classList.toggle("child", true);
    const square38 = document.createElement("div");
    square38.classList.toggle("child", true);
    const square39 = document.createElement("div");
    square39.classList.toggle("child", true);
    const square40 = document.createElement("div");
    square40.classList.toggle("child", true);
    const square41 = document.createElement("div");
    square41.classList.toggle("child", true);
    const square42 = document.createElement("div");
    square42.classList.toggle("child", true);
    const square43 = document.createElement("div");
    square43.classList.toggle("child", true);
    const square44 = document.createElement("div");
    square44.classList.toggle("child", true);
    const square45 = document.createElement("div");
    square45.classList.toggle("child", true);
    const square46 = document.createElement("div");
    square46.classList.toggle("child", true);
    const square47 = document.createElement("div");
    square47.classList.toggle("child", true);
    const square48 = document.createElement("div");
    square48.classList.toggle("child", true);
    const square49 = document.createElement("div");
    square49.classList.toggle("child", true);
    const square50 = document.createElement("div");
    square50.classList.toggle("child", true);
    const square51 = document.createElement("div");
    square51.classList.toggle("child", true);
    const square52 = document.createElement("div");
    square52.classList.toggle("child", true);
    const square53 = document.createElement("div");
    square53.classList.toggle("child", true);
    const square54 = document.createElement("div");
    square54.classList.toggle("child", true);
    const square55 = document.createElement("div");
    square55.classList.toggle("child", true);
    const square56 = document.createElement("div");
    square56.classList.toggle("child", true);
    const square57 = document.createElement("div");
    square57.classList.toggle("child", true);
    const square58 = document.createElement("div");
    square58.classList.toggle("child", true);
    const square59 = document.createElement("div");
    square59.classList.toggle("child", true);
    const square60 = document.createElement("div");
    square60.classList.toggle("child", true);
    const square61 = document.createElement("div");
    square61.classList.toggle("child", true);
    const square62 = document.createElement("div");
    square62.classList.toggle("child", true);
    const square63 = document.createElement("div");
    square63.classList.toggle("child", true);
    const square64 = document.createElement("div");
    square64.classList.toggle("child", true);
    const square65 = document.createElement("div");
    square65.classList.toggle("child", true);
    const square66 = document.createElement("div");
    square66.classList.toggle("child", true);
    const square67 = document.createElement("div");
    square67.classList.toggle("child", true);
    const square68 = document.createElement("div");
    square68.classList.toggle("child", true);
    const square69 = document.createElement("div");
    square69.classList.toggle("child", true);
    const square70 = document.createElement("div");
    square70.classList.toggle("child", true);
    const square71 = document.createElement("div");
    square71.classList.toggle("child", true);
    const square72 = document.createElement("div");
    square72.classList.toggle("child", true);
    const square73 = document.createElement("div");
    square73.classList.toggle("child", true);
    const square74 = document.createElement("div");
    square74.classList.toggle("child", true);
    const square75 = document.createElement("div");
    square75.classList.toggle("child", true);
    const square76 = document.createElement("div");
    square76.classList.toggle("child", true);
    const square77 = document.createElement("div");
    square77.classList.toggle("child", true);
    const square78 = document.createElement("div");
    square78.classList.toggle("child", true);
    const square79 = document.createElement("div");
    square79.classList.toggle("child", true);
    const square80 = document.createElement("div");
    square80.classList.toggle("child", true);
    const square81 = document.createElement("div");
    square81.classList.toggle("child", true);
    const square82 = document.createElement("div");
    square82.classList.toggle("child", true);
    const square83 = document.createElement("div");
    square83.classList.toggle("child", true);
    const square84 = document.createElement("div");
    square84.classList.toggle("child", true);
    const square85 = document.createElement("div");
    square85.classList.toggle("child", true);
    const square86 = document.createElement("div");
    square86.classList.toggle("child", true);
    const square87 = document.createElement("div");
    square87.classList.toggle("child", true);
    const square88 = document.createElement("div");
    square88.classList.toggle("child", true);
    const square89 = document.createElement("div");
    square89.classList.toggle("child", true);
    const square90 = document.createElement("div");
    square90.classList.toggle("child", true);
    const square91 = document.createElement("div");
    square91.classList.toggle("child", true);
    const square92 = document.createElement("div");
    square92.classList.toggle("child", true);
    const square93 = document.createElement("div");
    square93.classList.toggle("child", true);
    const square94 = document.createElement("div");
    square94.classList.toggle("child", true);
    const square95 = document.createElement("div");
    square95.classList.toggle("child", true);
    const square96 = document.createElement("div");
    square96.classList.toggle("child", true);
    const square97 = document.createElement("div");
    square97.classList.toggle("child", true);
    const square98 = document.createElement("div");
    square98.classList.toggle("child", true);
    const square99 = document.createElement("div");
    square99.classList.toggle("child", true);
    const square100 = document.createElement("div");
    square100.classList.toggle("child", true);
    const square101 = document.createElement("div");
    square101.classList.toggle("child", true);
    const square102 = document.createElement("div");
    square102.classList.toggle("child", true);
    const square103 = document.createElement("div");
    square103.classList.toggle("child", true);
    const square104 = document.createElement("div");
    square104.classList.toggle("child", true);
    const square105 = document.createElement("div");
    square105.classList.toggle("child", true);
    const square106 = document.createElement("div");
    square106.classList.toggle("child", true);
    const square107 = document.createElement("div");
    square107.classList.toggle("child", true);
    const square108 = document.createElement("div");
    square108.classList.toggle("child", true);
    const square109 = document.createElement("div");
    square109.classList.toggle("child", true);
    const square110 = document.createElement("div");
    square110.classList.toggle("child", true);
    const square111 = document.createElement("div");
    square111.classList.toggle("child", true);
    const square112 = document.createElement("div");
    square112.classList.toggle("child", true);
    const square113 = document.createElement("div");
    square113.classList.toggle("child", true);
    const square114 = document.createElement("div");
    square114.classList.toggle("child", true);
    const square115 = document.createElement("div");
    square115.classList.toggle("child", true);
    const square116 = document.createElement("div");
    square116.classList.toggle("child", true);
    const square117 = document.createElement("div");
    square117.classList.toggle("child", true);
    const square118 = document.createElement("div");
    square118.classList.toggle("child", true);
    const square119 = document.createElement("div");
    square119.classList.toggle("child", true);
    const square120 = document.createElement("div");
    square120.classList.toggle("child", true);
    const square121 = document.createElement("div");
    square121.classList.toggle("child", true);
    const square122 = document.createElement("div");
    square122.classList.toggle("child", true);
    const square123 = document.createElement("div");
    square123.classList.toggle("child", true);
    const square124 = document.createElement("div");
    square124.classList.toggle("child", true);
    const square125 = document.createElement("div");
    square125.classList.toggle("child", true);
    const square126 = document.createElement("div");
    square126.classList.toggle("child", true);
    const square127 = document.createElement("div");
    square127.classList.toggle("child", true);
    const square128 = document.createElement("div");
    square128.classList.toggle("child", true);
    const square129 = document.createElement("div");
    square129.classList.toggle("child", true);
    const square130 = document.createElement("div");
    square130.classList.toggle("child", true);
    const square131 = document.createElement("div");
    square131.classList.toggle("child", true);
    const square132 = document.createElement("div");
    square132.classList.toggle("child", true);
    const square133 = document.createElement("div");
    square133.classList.toggle("child", true);
    const square134 = document.createElement("div");
    square134.classList.toggle("child", true);
    const square135 = document.createElement("div");
    square135.classList.toggle("child", true);
    const square136 = document.createElement("div");
    square136.classList.toggle("child", true);
    const square137 = document.createElement("div");
    square137.classList.toggle("child", true);
    const square138 = document.createElement("div");
    square138.classList.toggle("child", true);
    const square139 = document.createElement("div");
    square139.classList.toggle("child", true);
    const square140 = document.createElement("div");
    square140.classList.toggle("child", true);
    const square141 = document.createElement("div");
    square141.classList.toggle("child", true);
    const square142 = document.createElement("div");
    square142.classList.toggle("child", true);
    const square143 = document.createElement("div");
    square143.classList.toggle("child", true);
    const square144 = document.createElement("div");
    square144.classList.toggle("child", true);
    const square145 = document.createElement("div");
    square145.classList.toggle("child", true);
    const square146 = document.createElement("div");
    square146.classList.toggle("child", true);
    const square147 = document.createElement("div");
    square147.classList.toggle("child", true);
    const square148 = document.createElement("div");
    square148.classList.toggle("child", true);
    const square149 = document.createElement("div");
    square149.classList.toggle("child", true);
    const square150 = document.createElement("div");
    square150.classList.toggle("child", true);
    const square151 = document.createElement("div");
    square151.classList.toggle("child", true);
    const square152 = document.createElement("div");
    square152.classList.toggle("child", true);
    const square153 = document.createElement("div");
    square153.classList.toggle("child", true);
    const square154 = document.createElement("div");
    square154.classList.toggle("child", true);
    const square155 = document.createElement("div");
    square155.classList.toggle("child", true);
    const square156 = document.createElement("div");
    square156.classList.toggle("child", true);
    const square157 = document.createElement("div");
    square157.classList.toggle("child", true);
    const square158 = document.createElement("div");
    square158.classList.toggle("child", true);
    const square159 = document.createElement("div");
    square159.classList.toggle("child", true);
    const square160 = document.createElement("div");
    square160.classList.toggle("child", true);
    const square161 = document.createElement("div");
    square161.classList.toggle("child", true);
    const square162 = document.createElement("div");
    square162.classList.toggle("child", true);
    const square163 = document.createElement("div");
    square163.classList.toggle("child", true);
    const square164 = document.createElement("div");
    square164.classList.toggle("child", true);
    const square165 = document.createElement("div");
    square165.classList.toggle("child", true);
    const square166 = document.createElement("div");
    square166.classList.toggle("child", true);
    const square167 = document.createElement("div");
    square167.classList.toggle("child", true);
    const square168 = document.createElement("div");
    square168.classList.toggle("child", true);
    const square169 = document.createElement("div");
    square169.classList.toggle("child", true);
    const square170 = document.createElement("div");
    square170.classList.toggle("child", true);
    const square171 = document.createElement("div");
    square171.classList.toggle("child", true);
    const square172 = document.createElement("div");
    square172.classList.toggle("child", true);
    const square173 = document.createElement("div");
    square173.classList.toggle("child", true);
    const square174 = document.createElement("div");
    square174.classList.toggle("child", true);
    const square175 = document.createElement("div");
    square175.classList.toggle("child", true);
    const square176 = document.createElement("div");
    square176.classList.toggle("child", true);
    const square177 = document.createElement("div");
    square177.classList.toggle("child", true);
    const square178 = document.createElement("div");
    square178.classList.toggle("child", true);
    const square179 = document.createElement("div");
    square179.classList.toggle("child", true);
    const square180 = document.createElement("div");
    square180.classList.toggle("child", true);
    const square181 = document.createElement("div");
    square181.classList.toggle("child", true);
    const square182 = document.createElement("div");
    square182.classList.toggle("child", true);
    const square183 = document.createElement("div");
    square183.classList.toggle("child", true);
    const square184 = document.createElement("div");
    square184.classList.toggle("child", true);
    const square185 = document.createElement("div");
    square185.classList.toggle("child", true);
    const square186 = document.createElement("div");
    square186.classList.toggle("child", true);
    const square187 = document.createElement("div");
    square187.classList.toggle("child", true);
    const square188 = document.createElement("div");
    square188.classList.toggle("child", true);
    const square189 = document.createElement("div");
    square189.classList.toggle("child", true);
    const square190 = document.createElement("div");
    square190.classList.toggle("child", true);
    const square191 = document.createElement("div");
    square191.classList.toggle("child", true);
    const square192 = document.createElement("div");
    square192.classList.toggle("child", true);
    const square193 = document.createElement("div");
    square193.classList.toggle("child", true);
    const square194 = document.createElement("div");
    square194.classList.toggle("child", true);
    const square195 = document.createElement("div");
    square195.classList.toggle("child", true);
    const square196 = document.createElement("div");
    square196.classList.toggle("child", true);
    const square197 = document.createElement("div");
    square197.classList.toggle("child", true);
    const square198 = document.createElement("div");
    square198.classList.toggle("child", true);
    const square199 = document.createElement("div");
    square199.classList.toggle("child", true);
    const square200 = document.createElement("div");
    square200.classList.toggle("child", true);
    const square201 = document.createElement("div");
    square201.classList.toggle("child", true);
    const square202 = document.createElement("div");
    square202.classList.toggle("child", true);
    const square203 = document.createElement("div");
    square203.classList.toggle("child", true);
    const square204 = document.createElement("div");
    square204.classList.toggle("child", true);
    const square205 = document.createElement("div");
    square205.classList.toggle("child", true);
    const square206 = document.createElement("div");
    square206.classList.toggle("child", true);
    const square207 = document.createElement("div");
    square207.classList.toggle("child", true);
    const square208 = document.createElement("div");
    square208.classList.toggle("child", true);
    const square209 = document.createElement("div");
    square209.classList.toggle("child", true);
    const square210 = document.createElement("div");
    square210.classList.toggle("child", true);
    const square211 = document.createElement("div");
    square211.classList.toggle("child", true);
    const square212 = document.createElement("div");
    square212.classList.toggle("child", true);
    const square213 = document.createElement("div");
    square213.classList.toggle("child", true);
    const square214 = document.createElement("div");
    square214.classList.toggle("child", true);
    const square215 = document.createElement("div");
    square215.classList.toggle("child", true);
    const square216 = document.createElement("div");
    square216.classList.toggle("child", true);
    const square217 = document.createElement("div");
    square217.classList.toggle("child", true);
    const square218 = document.createElement("div");
    square218.classList.toggle("child", true);
    const square219 = document.createElement("div");
    square219.classList.toggle("child", true);
    const square220 = document.createElement("div");
    square220.classList.toggle("child", true);
    const square221 = document.createElement("div");
    square221.classList.toggle("child", true);
    const square222 = document.createElement("div");
    square222.classList.toggle("child", true);
    const square223 = document.createElement("div");
    square223.classList.toggle("child", true);
    const square224 = document.createElement("div");
    square224.classList.toggle("child", true);
    const square225 = document.createElement("div");
    square225.classList.toggle("child", true);
    const square226 = document.createElement("div");
    square226.classList.toggle("child", true);
    const square227 = document.createElement("div");
    square227.classList.toggle("child", true);
    const square228 = document.createElement("div");
    square228.classList.toggle("child", true);
    const square229 = document.createElement("div");
    square229.classList.toggle("child", true);
    const square230 = document.createElement("div");
    square230.classList.toggle("child", true);
    const square231 = document.createElement("div");
    square231.classList.toggle("child", true);
    const square232 = document.createElement("div");
    square232.classList.toggle("child", true);
    const square233 = document.createElement("div");
    square233.classList.toggle("child", true);
    const square234 = document.createElement("div");
    square234.classList.toggle("child", true);
    const square235 = document.createElement("div");
    square235.classList.toggle("child", true);
    const square236 = document.createElement("div");
    square236.classList.toggle("child", true);
    const square237 = document.createElement("div");
    square237.classList.toggle("child", true);
    const square238 = document.createElement("div");
    square238.classList.toggle("child", true);
    const square239 = document.createElement("div");
    square239.classList.toggle("child", true);
    const square240 = document.createElement("div");
    square240.classList.toggle("child", true);
    const square241 = document.createElement("div");
    square241.classList.toggle("child", true);
    const square242 = document.createElement("div");
    square242.classList.toggle("child", true);
    const square243 = document.createElement("div");
    square243.classList.toggle("child", true);
    const square244 = document.createElement("div");
    square244.classList.toggle("child", true);
    const square245 = document.createElement("div");
    square245.classList.toggle("child", true);
    const square246 = document.createElement("div");
    square246.classList.toggle("child", true);
    const square247 = document.createElement("div");
    square247.classList.toggle("child", true);
    const square248 = document.createElement("div");
    square248.classList.toggle("child", true);
    const square249 = document.createElement("div");
    square249.classList.toggle("child", true);
    const square250 = document.createElement("div");
    square250.classList.toggle("child", true);
    const square251 = document.createElement("div");
    square251.classList.toggle("child", true);
    const square252 = document.createElement("div");
    square252.classList.toggle("child", true);
    const square253 = document.createElement("div");
    square253.classList.toggle("child", true);
    const square254 = document.createElement("div");
    square254.classList.toggle("child", true);
    const square255 = document.createElement("div");
    square255.classList.toggle("child", true);
    const square256 = document.createElement("div");
    square256.classList.toggle("child", true);
    parentGrid.append(square1, square2, square3, square4, square5, square6, square7, square8, square9, square10, square11, square12, square13, square14, square15, square16, square17, square18, square19, square20);
    parentGrid.append(square21, square22, square23, square24, square25, square26, square27, square28, square29, square30, square31, square32, square33, square34, square35, square36, square37, square38, square39, square40);
    parentGrid.append(square41, square42, square43, square44, square45, square46, square47, square48, square49, square50, square51, square52, square53, square54, square55, square56, square57, square58, square59, square60);
    parentGrid.append(square61, square62, square63, square64, square65, square66, square67, square68, square69, square70, square71, square72, square73, square74, square75, square76, square77, square78, square79, square80);
    parentGrid.append(square81, square82, square83, square84, square85, square86, square87, square88, square89, square90, square91, square92, square93, square94, square95, square96, square97, square98, square99, square100);
    parentGrid.append(square101, square102, square103, square104, square105, square106, square107, square108, square109, square110, square111, square112, square113, square114, square115, square116, square117, square118, square119, square120);
    parentGrid.append(square121, square122, square123, square124, square125, square126, square127, square128, square129, square130, square131, square132, square133, square134, square135, square136, square137, square138, square139, square140);
    parentGrid.append(square141, square142, square143, square144, square145, square146, square147, square148, square149, square150, square151, square152, square153, square154, square155, square156, square157, square158, square159, square160);
    parentGrid.append(square161, square162, square163, square164, square165, square166, square167, square168, square169, square170, square171, square172, square173, square174, square175, square176, square177, square178, square179, square180);
    parentGrid.append(square181, square182, square183, square184, square185, square186, square187, square188, square189, square190, square191, square192, square193, square194, square195, square196, square197, square198, square199, square200);
    parentGrid.append(square201, square202, square203, square204, square205, square206, square207, square208, square209, square210, square211, square212, square213, square214, square215, square216, square217, square218, square219, square220);
    parentGrid.append(square221, square222, square223, square224, square225, square226, square227, square228, square229, square230, square231, square232, square233, square234, square235, square236, square237, square238, square239, square240);
    parentGrid.append(square241, square242, square243, square244, square245, square246, square247, square248, square249, square250, square251, square252, square253, square254, square255, square256);

    //add parentGrid to the visible body of the html
    center.appendChild(parentGrid);


    //adds a hover event to the children divs of the grid so that there is a background color change when the mouse hovers   
    const children = document.querySelectorAll(".child");
    for (i=0; i<children.length ; i++) {
        children[i].addEventListener(
            "mouseover",
            (event) => {
                event.target.style.backgroundColor = "#999494";
                setTimeout(() => {
                    event.target.style.backgroundColor = "";
                }, 1000);
            },
            false,
        );
    }
    
    // children.addEventListener(
    //     "mouseover",
    //     (event) => {
    //         event.target.style.backgroundColor = "#999494";
    //         setTimeout(() => {
    //             event.target.style.backgroundColor = "";
    //         }, 1000);
    //     },
    //     false,
    // );



    //testing
    console.log();
